# model parameters
model: 
  # name of model class
  name: FCDenseNet67
  # number of input channels
  in_channels: 1
  # number of output channels
  out_channels: 1

# loss functions
losses:
    # name of loss class
  - name: MSSSIM
    # multiplier of the exact loss
    alpha: 0.95
  - name: L1Loss
    alpha: 0.05
# optimizer parameters
optimizer:
  # name of optimizer class
  name: Adam
  # learning rate
  lr: 3e-4
# learning rate scheduler
scheduler:
  # name of scheduler class
  name: MultiStepLR
  # number of epochs before changing learning rate
  milestones: [10]
  # multiplier of changing
  gamma: 0.5

# number of epochs for training
epochs: 30
# batch size
batch_size: 1
# number of workers
num_workers: 8
# number of iterations over the training set
train_iter: 1

# random seed for reproducebility
seed: 242

# DataLoader parameters
dataset:
  name: FCDataset
  train_csv_file: ./data/train.csv
  val_csv_file: ./data/val.csv
  test_csv_file: ./data/test.csv
  root_dir: ./data/images
  augmentations:
    # augmentations to apply on the image during training phase
    train:
      # input size, length of largest size
      - name: LongestMaxSize
        max_size: 576
        p: 1
      # min_height and min_width should be the same as max_size of previous augmentation
      - name: PadIfNeeded
        min_height: 576
        min_width: 576
      - name: HorizontalFlip
        p: 0.5
      - name: ShiftScaleRotate
        shift_limit: 0.05
        scale_limit: 0.1
        rotate_limit: 20
        interpolation: 1
        border_mode: 4
        p: 1
      - name: OneOf
        augs:
          - name: RandomBrightnessContrast
            brightness_limit: 0.1
            contrast_limit: 0.0
            p: 1
          - name: RandomGamma
      # normalization parameters
      - name: Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    # augmentations to apply on the image during validation and testing phases
    # basically, just transform the image, so it can fit the network's output 
    validation:
      - name: LongestMaxSize
        max_size: 576
        p: 1
      - name: PadIfNeeded
        min_height: 576
        min_width: 576
      - name: Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
