!!python/object/apply:collections.OrderedDict
- - - model
    - !!python/object/apply:collections.OrderedDict
      - - - name
          - myAutoencoderTied
        - - in_channels
          - 4
        - - out_channels
          - 4
        - - final_activation
          - linear
  - - losses
    - - !!python/object/apply:collections.OrderedDict
        - - - name
            - MSSSIM
          - - alpha
            - 0.99
      - !!python/object/apply:collections.OrderedDict
        - - - name
            - L1Loss
          - - alpha
            - 0.01
  - - optimizer
    - !!python/object/apply:collections.OrderedDict
      - - - name
          - Adam
        - - lr
          - 0.001
  - - scheduler
    - !!python/object/apply:collections.OrderedDict
      - - - name
          - MultiStepLR
        - - milestones
          - - 75
            - 90
        - - gamma
          - 0.1
  - - epochs
    - 2
  - - batch_size
    - 12
  - - num_workers
    - 10
  - - train_iter
    - 2
  - - seed
    - 242
  - - dataset
    - !!python/object/apply:collections.OrderedDict
      - - - name
          - WaveletDataset
        - - root_dir
          - /home/ilyas/ribs_suppression/training_pipeline/data/images
        - - mean
          - !!python/tuple
            - 0
            - 0
            - 0
        - - std
          - !!python/tuple
            - 1
            - 1
            - 1
        - - max_pixel_value
          - 1.0
        - - repeat_dataset
          - 100
        - - train_csv_file
          - /home/ilyas/ribs_suppression/training_pipeline/data/train.csv
        - - val_csv_file
          - /home/ilyas/ribs_suppression/training_pipeline/data/val.csv
        - - test_csv_file
          - /home/ilyas/ribs_suppression/training_pipeline/data/test.csv
        - - augmentations
          - !!python/object/apply:collections.OrderedDict
            - - - train
                - - !!python/object/apply:collections.OrderedDict
                    - - - name
                        - CLAHE
                      - - clip_limit
                        - 0.1
                      - - tile_grid_size
                        - !!python/tuple
                          - 8
                          - 8
                      - - p
                        - 1
                  - !!python/object/apply:collections.OrderedDict
                    - - - name
                        - OneOf
                      - - augs
                        - - !!python/object/apply:collections.OrderedDict
                            - - - name
                                - GaussNoise
                              - - p
                                - 0.5
                          - !!python/object/apply:collections.OrderedDict
                            - - - name
                                - Blur
                              - - blur_limit
                                - 7
                  - !!python/object/apply:collections.OrderedDict
                    - - - name
                        - HorizontalFlip
                      - - p
                        - 0.5
                  - !!python/object/apply:collections.OrderedDict
                    - - - name
                        - ShiftScaleRotate
                      - - shift_limit
                        - 0.05
                      - - scale_limit
                        - 0.4
                      - - rotate_limit
                        - 20
                      - - interpolation
                        - 1
                      - - border_mode
                        - 4
                      - - p
                        - 1
                  - !!python/object/apply:collections.OrderedDict
                    - - - name
                        - OneOf
                      - - augs
                        - - !!python/object/apply:collections.OrderedDict
                            - - - name
                                - RandomBrightnessContrast
                              - - brightness_limit
                                - 0.4
                              - - contrast_limit
                                - 0.4
                              - - p
                                - 0.5
                          - !!python/object/apply:collections.OrderedDict
                            - - - name
                                - RandomGamma
                              - - p
                                - 0.5
                  - !!python/object/apply:collections.OrderedDict
                    - - - name
                        - OneOf
                      - - augs
                        - - !!python/object/apply:collections.OrderedDict
                            - - - name
                                - GridDistortion
                              - - distort_limit
                                - 0.4
                              - - border_mode
                                - 4
                              - - p
                                - 0.5
                          - !!python/object/apply:collections.OrderedDict
                            - - - name
                                - ElasticTransform
                              - - sigma
                                - 60
                              - - border_mode
                                - 4
                              - - p
                                - 0.5
              - - validation
                - - !!python/object/apply:collections.OrderedDict
                    - - - name
                        - LongestMaxSize
                      - - max_size
                        - 576
                      - - p
                        - 1
  - - logs
    - !!python/object/apply:collections.OrderedDict
      - - - logdir
          - /home/ilyas/ribs_suppression/training_pipeline/snapshots/
